import { EnemyTemplate } from '../types';

// 120+ unique enemies across 5 tiers and 8 types
// Types: MECHANICAL | HUMANOID | ANOMALY | DRONE | DROID | BEAST | PHANTOM | CONSTRUCT

export const ENEMY_ROSTER: EnemyTemplate[] = [

  // ─── TIER 1 (Level 1-4) ───────────────────────────────────────────────────

  { id: 'scav_drone_mk1', name: 'Scav Drone MK-I', flavor: 'A decommissioned city drone repurposed by scavengers. Erratic flight pattern, weak armor.', type: 'DRONE', tier: 1, baseHp: 280, baseAtk: 120, baseDef: 20, abilities: ['Spark Burst', 'Dive Bomb'], captureRate: 0.7, lootTable: ['nano_chip', 'drone_part'], xpReward: 40, currencyReward: 25 },
  { id: 'rust_crawler', name: 'Rust Crawler', flavor: 'Six-legged maintenance bot gone feral. Coats enemies in oxidizing spray.', type: 'MECHANICAL', tier: 1, baseHp: 340, baseAtk: 100, baseDef: 45, abilities: ['Rust Spray', 'Pincer Clamp'], captureRate: 0.65, lootTable: ['scrap_metal', 'nano_chip'], xpReward: 45, currencyReward: 20 },
  { id: 'glitch_sprite', name: 'Glitch Sprite', flavor: 'A corrupted data fragment given physical form. Flickers in and out of reality.', type: 'ANOMALY', tier: 1, baseHp: 200, baseAtk: 180, baseDef: 10, abilities: ['Data Spike', 'Flicker Step'], captureRate: 0.6, lootTable: ['corrupted_data', 'nano_chip'], xpReward: 50, currencyReward: 30 },
  { id: 'patrol_bot_beta', name: 'Patrol Bot Beta', flavor: 'Standard-issue security bot running outdated firmware. Predictable attack patterns.', type: 'DROID', tier: 1, baseHp: 420, baseAtk: 130, baseDef: 60, abilities: ['Warning Shot', 'Stun Baton'], captureRate: 0.55, lootTable: ['power_cell', 'scrap_metal'], xpReward: 55, currencyReward: 35 },
  { id: 'nano_swarm', name: 'Nano Swarm', flavor: 'Thousands of microscopic bots acting as one. Hard to hit, easy to scatter.', type: 'CONSTRUCT', tier: 1, baseHp: 180, baseAtk: 210, baseDef: 5, abilities: ['Swarm Engulf', 'Micro Drill'], captureRate: 0.5, lootTable: ['nano_chip', 'nano_chip'], xpReward: 60, currencyReward: 40 },
  { id: 'hollow_shell', name: 'Hollow Shell', flavor: 'An empty combat chassis animated by residual charge. No brain — pure aggression.', type: 'MECHANICAL', tier: 1, baseHp: 500, baseAtk: 90, baseDef: 80, abilities: ['Body Slam', 'Iron Wall'], captureRate: 0.6, lootTable: ['scrap_metal', 'power_cell'], xpReward: 48, currencyReward: 22 },
  { id: 'echo_wisp', name: 'Echo Wisp', flavor: 'A ghost signal trapped in hardware. Mimics the last sound it recorded.', type: 'PHANTOM', tier: 1, baseHp: 150, baseAtk: 220, baseDef: 0, abilities: ['Echo Scream', 'Signal Jam'], captureRate: 0.55, lootTable: ['corrupted_data', 'echo_fragment'], xpReward: 65, currencyReward: 45 },
  { id: 'tangle_wire', name: 'Tangle Wire', flavor: 'A ball of self-replicating cable that strangles anything it wraps around.', type: 'CONSTRUCT', tier: 1, baseHp: 260, baseAtk: 150, baseDef: 30, abilities: ['Constrict', 'Electric Coil'], captureRate: 0.65, lootTable: ['scrap_metal', 'nano_chip'], xpReward: 42, currencyReward: 18 },
  { id: 'grunt_unit_7', name: 'Grunt Unit-7', flavor: 'Mass-produced combat droid. Cheap, expendable, and surprisingly stubborn.', type: 'DROID', tier: 1, baseHp: 380, baseAtk: 140, baseDef: 50, abilities: ['Suppressive Fire', 'Charge'], captureRate: 0.6, lootTable: ['power_cell', 'drone_part'], xpReward: 52, currencyReward: 28 },
  { id: 'leech_bot', name: 'Leech Bot', flavor: 'Latches onto power sources and drains them dry. Grows stronger the more it feeds.', type: 'MECHANICAL', tier: 1, baseHp: 300, baseAtk: 160, baseDef: 25, abilities: ['Power Drain', 'Latch'], captureRate: 0.5, lootTable: ['power_cell', 'energy_shard'], xpReward: 58, currencyReward: 38 },

  // ─── TIER 1 continued ─────────────────────────────────────────────────────

  { id: 'spore_mite', name: 'Spore Mite', flavor: 'Bio-mechanical hybrid. Releases toxic spores when threatened.', type: 'BEAST', tier: 1, baseHp: 220, baseAtk: 170, baseDef: 15, abilities: ['Spore Cloud', 'Bite'], captureRate: 0.7, lootTable: ['bio_sample', 'nano_chip'], xpReward: 47, currencyReward: 22 },
  { id: 'static_hound', name: 'Static Hound', flavor: 'Four-legged predator built from salvaged military parts. Hunts by heat signature.', type: 'BEAST', tier: 1, baseHp: 310, baseAtk: 190, baseDef: 20, abilities: ['Pounce', 'Static Bite', 'Howl'], captureRate: 0.6, lootTable: ['bio_sample', 'scrap_metal'], xpReward: 62, currencyReward: 32 },
  { id: 'loop_ghost', name: 'Loop Ghost', flavor: 'Trapped in an infinite execution loop. Replays the same attack endlessly.', type: 'PHANTOM', tier: 1, baseHp: 170, baseAtk: 200, baseDef: 0, abilities: ['Loop Strike', 'Infinite Repeat'], captureRate: 0.45, lootTable: ['corrupted_data', 'echo_fragment'], xpReward: 70, currencyReward: 50 },
  { id: 'cog_golem', name: 'Cog Golem', flavor: 'Industrial machine that gained rudimentary awareness. Slow but devastating.', type: 'CONSTRUCT', tier: 1, baseHp: 600, baseAtk: 80, baseDef: 100, abilities: ['Gear Crush', 'Steam Vent'], captureRate: 0.55, lootTable: ['scrap_metal', 'scrap_metal', 'power_cell'], xpReward: 55, currencyReward: 25 },
  { id: 'zip_drone', name: 'Zip Drone', flavor: 'Delivery drone weaponized with contact explosives. Kamikaze attack pattern.', type: 'DRONE', tier: 1, baseHp: 140, baseAtk: 280, baseDef: 5, abilities: ['Kamikaze Dive', 'Flash Blind'], captureRate: 0.4, lootTable: ['explosive_core', 'drone_part'], xpReward: 75, currencyReward: 55 },

  // ─── TIER 2 (Level 5-9) ───────────────────────────────────────────────────

  { id: 'sentinel_v2', name: 'Sentinel V.2', flavor: 'Upgraded patrol unit with adaptive combat AI. Learns from each failed attack.', type: 'DROID', tier: 2, baseHp: 750, baseAtk: 320, baseDef: 140, abilities: ['Adaptive Strike', 'Counter Protocol', 'Shield Deploy'], captureRate: 0.45, lootTable: ['power_cell', 'ai_core', 'nano_chip'], xpReward: 120, currencyReward: 80 },
  { id: 'void_leech', name: 'Void Leech', flavor: 'An organism from the anomaly zone. Feeds on psychic energy and electromagnetic fields.', type: 'ANOMALY', tier: 2, baseHp: 580, baseAtk: 420, baseDef: 80, abilities: ['Mind Drain', 'Void Latch', 'Psychic Burst'], captureRate: 0.4, lootTable: ['void_shard', 'corrupted_data'], xpReward: 140, currencyReward: 95 },
  { id: 'steel_raptor', name: 'Steel Raptor', flavor: 'Avian hunter chassis. Swoops at hypersonic speed, precision talons tear through armor.', type: 'BEAST', tier: 2, baseHp: 620, baseAtk: 480, baseDef: 60, abilities: ['Sonic Dive', 'Talon Rend', 'Feather Blade'], captureRate: 0.38, lootTable: ['alloy_plate', 'bio_sample'], xpReward: 155, currencyReward: 105 },
  { id: 'plasma_wraith', name: 'Plasma Wraith', flavor: 'A plasma field given sentience. Burns through shields and leaves scorch trails.', type: 'PHANTOM', tier: 2, baseHp: 500, baseAtk: 560, baseDef: 30, abilities: ['Plasma Touch', 'Scorch Trail', 'Ignite'], captureRate: 0.35, lootTable: ['plasma_cell', 'echo_fragment'], xpReward: 165, currencyReward: 120 },
  { id: 'iron_behemoth', name: 'Iron Behemoth', flavor: 'Siege-class war machine. Each footstep craters the ground.', type: 'MECHANICAL', tier: 2, baseHp: 1200, baseAtk: 280, baseDef: 260, abilities: ['Seismic Stomp', 'Cannon Blast', 'Iron Fortress'], captureRate: 0.3, lootTable: ['alloy_plate', 'scrap_metal', 'power_cell'], xpReward: 130, currencyReward: 90 },
  { id: 'mirror_droid', name: 'Mirror Droid', flavor: 'Copies and amplifies the last ability used against it. Fighting it is fighting yourself.', type: 'DROID', tier: 2, baseHp: 680, baseAtk: 380, baseDef: 120, abilities: ['Mirror Strike', 'Copy Protocol', 'Reflect Barrier'], captureRate: 0.42, lootTable: ['ai_core', 'nano_chip'], xpReward: 145, currencyReward: 100 },
  { id: 'acid_crawler', name: 'Acid Crawler', flavor: 'Secretes highly corrosive fluid that dissolves metal on contact.', type: 'BEAST', tier: 2, baseHp: 540, baseAtk: 400, baseDef: 70, abilities: ['Acid Spit', 'Dissolve', 'Slick Trail'], captureRate: 0.45, lootTable: ['acid_vial', 'bio_sample'], xpReward: 125, currencyReward: 75 },
  { id: 'phantom_rider', name: 'Phantom Rider', flavor: 'A spectral humanoid fused with a destroyed vehicle. Half ghost, half machine.', type: 'PHANTOM', tier: 2, baseHp: 720, baseAtk: 440, baseDef: 95, abilities: ['Ghost Charge', 'Phase Through', 'Wail'], captureRate: 0.35, lootTable: ['echo_fragment', 'void_shard'], xpReward: 150, currencyReward: 110 },
  { id: 'recon_spider', name: 'Recon Spider', flavor: 'Eight-legged surveillance unit armed with electro-web launchers.', type: 'MECHANICAL', tier: 2, baseHp: 590, baseAtk: 350, baseDef: 110, abilities: ['Web Trap', 'Electro Net', 'Leg Stab'], captureRate: 0.5, lootTable: ['nano_chip', 'power_cell'], xpReward: 118, currencyReward: 78 },
  { id: 'berserker_unit', name: 'Berserker Unit', flavor: 'Combat droid with its safety limiters removed. Attacks until one of you stops moving.', type: 'DROID', tier: 2, baseHp: 900, baseAtk: 510, baseDef: 80, abilities: ['Frenzied Strike', 'Overload', 'Blood Rage'], captureRate: 0.28, lootTable: ['ai_core', 'power_cell', 'alloy_plate'], xpReward: 170, currencyReward: 130 },

  // ─── TIER 2 continued ─────────────────────────────────────────────────────

  { id: 'data_wraith', name: 'Data Wraith', flavor: 'Born from deleted files and corrupt memory. Exists only to erase.', type: 'ANOMALY', tier: 2, baseHp: 460, baseAtk: 530, baseDef: 20, abilities: ['Delete', 'Memory Wipe', 'Corrupt'], captureRate: 0.32, lootTable: ['corrupted_data', 'echo_fragment', 'void_shard'], xpReward: 160, currencyReward: 125 },
  { id: 'shieldbreaker', name: 'Shieldbreaker', flavor: 'Engineered specifically to defeat defensive systems. Every attack targets weak points.', type: 'DROID', tier: 2, baseHp: 700, baseAtk: 460, baseDef: 100, abilities: ['Armor Pierce', 'Shield Crack', 'Exploit Weakness'], captureRate: 0.38, lootTable: ['ai_core', 'alloy_plate'], xpReward: 148, currencyReward: 102 },
  { id: 'ember_beast', name: 'Ember Beast', flavor: 'Thermal-core lifeform. Its body burns at 800 degrees. Touch it and you find out.', type: 'BEAST', tier: 2, baseHp: 660, baseAtk: 490, baseDef: 85, abilities: ['Incinerate', 'Heat Wave', 'Melt'], captureRate: 0.35, lootTable: ['plasma_cell', 'energy_shard'], xpReward: 152, currencyReward: 108 },
  { id: 'glitch_titan', name: 'Glitch Titan', flavor: 'An oversized Glitch Sprite that refused to stay small. Reality bends around it.', type: 'ANOMALY', tier: 2, baseHp: 850, baseAtk: 400, baseDef: 150, abilities: ['Reality Bend', 'Mass Glitch', 'Spatial Crush'], captureRate: 0.3, lootTable: ['void_shard', 'corrupted_data'], xpReward: 175, currencyReward: 135 },
  { id: 'storm_drone', name: 'Storm Drone', flavor: 'Military-grade UAV fitted with atmospheric disruption tech. Calls down lightning.', type: 'DRONE', tier: 2, baseHp: 580, baseAtk: 520, baseDef: 55, abilities: ['Lightning Strike', 'Static Cloud', 'Ion Cannon'], captureRate: 0.32, lootTable: ['energy_shard', 'power_cell'], xpReward: 162, currencyReward: 118 },

  // ─── TIER 3 (Level 10-14) ─────────────────────────────────────────────────

  { id: 'abyss_stalker', name: 'Abyss Stalker', flavor: 'Predator native to the void zones. Invisible until it attacks. Has never been caught alive.', type: 'PHANTOM', tier: 3, baseHp: 1100, baseAtk: 780, baseDef: 200, abilities: ['Shadow Pounce', 'Void Cloak', 'Terror Bite', 'Phase Kill'], captureRate: 0.22, lootTable: ['void_shard', 'echo_fragment', 'dark_crystal'], xpReward: 280, currencyReward: 200 },
  { id: 'quantum_golem', name: 'Quantum Golem', flavor: 'Exists in two states simultaneously. Can attack and defend at the same time.', type: 'CONSTRUCT', tier: 3, baseHp: 1600, baseAtk: 650, baseDef: 380, abilities: ['Dual State', 'Quantum Smash', 'Entangle', 'Superposition'], captureRate: 0.2, lootTable: ['quantum_core', 'alloy_plate'], xpReward: 300, currencyReward: 220 },
  { id: 'neural_serpent', name: 'Neural Serpent', flavor: 'A long-range AI weapon system shaped like a serpent. Hacks your combat implants mid-fight.', type: 'MECHANICAL', tier: 3, baseHp: 980, baseAtk: 860, baseDef: 160, abilities: ['Neural Hack', 'Constrict', 'Venom Injection', 'Override'], captureRate: 0.25, lootTable: ['ai_core', 'void_shard', 'neural_chip'], xpReward: 290, currencyReward: 210 },
  { id: 'colossus_mk3', name: 'Colossus MK-III', flavor: 'Third-generation war golem. Powered by three fusion cores. Retired from service, not from combat.', type: 'DROID', tier: 3, baseHp: 2200, baseAtk: 600, baseDef: 480, abilities: ['Fusion Cannon', 'Iron Tide', 'Core Overload', 'Last Stand'], captureRate: 0.15, lootTable: ['fusion_core', 'alloy_plate', 'power_cell'], xpReward: 320, currencyReward: 240 },
  { id: 'revenant_ghost', name: 'Revenant Ghost', flavor: 'The digital echo of a warrior who refused to die. Fights with techniques from a forgotten era.', type: 'PHANTOM', tier: 3, baseHp: 900, baseAtk: 950, baseDef: 120, abilities: ['Death Slash', 'Haunting Wail', 'Possess', 'Last Rite'], captureRate: 0.2, lootTable: ['echo_fragment', 'dark_crystal', 'void_shard'], xpReward: 310, currencyReward: 230 },
  { id: 'apex_predator', name: 'Apex Predator', flavor: 'Bio-engineered killing machine. Top of the food chain in every zone it enters.', type: 'BEAST', tier: 3, baseHp: 1400, baseAtk: 820, baseDef: 240, abilities: ['Apex Strike', 'Feral Rush', 'Hunter Instinct', 'Savage Tear'], captureRate: 0.18, lootTable: ['bio_sample', 'dark_crystal', 'alloy_plate'], xpReward: 305, currencyReward: 225 },
  { id: 'override_unit', name: 'OVERRIDE Unit', flavor: 'A rogue AI that commandeers other machines mid-battle to fight for it.', type: 'DROID', tier: 3, baseHp: 1050, baseAtk: 740, baseDef: 300, abilities: ['Commandeer', 'Network Pulse', 'System Override', 'Digital Army'], captureRate: 0.22, lootTable: ['ai_core', 'neural_chip', 'quantum_core'], xpReward: 295, currencyReward: 215 },
  { id: 'singularity_mite', name: 'Singularity Mite', flavor: 'Impossibly small. Creates localized black holes. Size is not a factor in its threat level.', type: 'ANOMALY', tier: 3, baseHp: 700, baseAtk: 1100, baseDef: 80, abilities: ['Micro Singularity', 'Gravity Crush', 'Event Horizon', 'Collapse'], captureRate: 0.18, lootTable: ['void_shard', 'quantum_core'], xpReward: 330, currencyReward: 260 },
  { id: 'pyro_sentinel', name: 'Pyro Sentinel', flavor: 'Fire-class guardian unit. Its armor superheats on contact. Melts the ground it stands on.', type: 'MECHANICAL', tier: 3, baseHp: 1300, baseAtk: 710, baseDef: 360, abilities: ['Molten Strike', 'Inferno Wall', 'Core Melt', 'Supernova'], captureRate: 0.2, lootTable: ['plasma_cell', 'fusion_core', 'energy_shard'], xpReward: 285, currencyReward: 205 },
  { id: 'specter_swarm', name: 'Specter Swarm', flavor: 'Thousands of micro-ghosts moving as one mass. Each one alone is nothing. Together, terrifying.', type: 'PHANTOM', tier: 3, baseHp: 800, baseAtk: 900, baseDef: 100, abilities: ['Mass Haunt', 'Swarm Crush', 'Phasing Cloud', 'Soul Drain'], captureRate: 0.15, lootTable: ['echo_fragment', 'echo_fragment', 'dark_crystal'], xpReward: 315, currencyReward: 235 },

  // ─── TIER 3 continued ─────────────────────────────────────────────────────

  { id: 'volt_hydra', name: 'Volt Hydra', flavor: 'Multi-headed electrical beast. Cut one head off, it splits into two.', type: 'BEAST', tier: 3, baseHp: 1500, baseAtk: 750, baseDef: 200, abilities: ['Triple Bite', 'Regenerate', 'Chain Lightning', 'Split'], captureRate: 0.2, lootTable: ['energy_shard', 'bio_sample', 'dark_crystal'], xpReward: 298, currencyReward: 218 },
  { id: 'fracture_drone', name: 'Fracture Drone', flavor: 'Splits into three smaller drones on taking heavy damage. Harder to hit than one.', type: 'DRONE', tier: 3, baseHp: 1100, baseAtk: 680, baseDef: 180, abilities: ['Split Formation', 'Scatter Fire', 'Recombine', 'Coordinated Strike'], captureRate: 0.25, lootTable: ['drone_part', 'power_cell', 'ai_core'], xpReward: 275, currencyReward: 195 },
  { id: 'null_entity', name: 'Null Entity', flavor: 'Has no origin in any known database. Shouldn\'t exist. Attacks with weapons that also shouldn\'t exist.', type: 'ANOMALY', tier: 3, baseHp: 1200, baseAtk: 880, baseDef: 140, abilities: ['Null Strike', 'Erase', 'Paradox', 'Unexist'], captureRate: 0.12, lootTable: ['void_shard', 'quantum_core', 'dark_crystal'], xpReward: 340, currencyReward: 270 },

  // ─── TIER 4 (Level 15-19) ─────────────────────────────────────────────────

  { id: 'behemoth_prime', name: 'Behemoth Prime', flavor: 'The largest mobile weapons platform ever deployed. Classified. Should be offline. Is not.', type: 'MECHANICAL', tier: 4, baseHp: 3500, baseAtk: 1200, baseDef: 700, abilities: ['Planet Breaker', 'Orbital Shell', 'Total Suppression', 'Fortress Protocol'], captureRate: 0.1, lootTable: ['fusion_core', 'alloy_plate', 'quantum_core'], xpReward: 550, currencyReward: 420 },
  { id: 'omega_wraith', name: 'Omega Wraith', flavor: 'The final form of digital death. Has killed eleven named operatives. This is your warning.', type: 'PHANTOM', tier: 4, baseHp: 2200, baseAtk: 1600, baseDef: 300, abilities: ['Omega Strike', 'Soul Shatter', 'Death Field', 'Eternal Haunt', 'Possession'], captureRate: 0.08, lootTable: ['dark_crystal', 'void_shard', 'echo_fragment'], xpReward: 600, currencyReward: 480 },
  { id: 'genesis_core', name: 'Genesis Core', flavor: 'The original AI from which all others were derived. Ancient, dormant, and now very annoyed.', type: 'CONSTRUCT', tier: 4, baseHp: 4000, baseAtk: 1100, baseDef: 900, abilities: ['Creation Burst', 'Primal Code', 'System Genesis', 'Reset All'], captureRate: 0.07, lootTable: ['quantum_core', 'neural_chip', 'ai_core'], xpReward: 580, currencyReward: 460 },
  { id: 'apex_cyborg', name: 'Apex Cyborg', flavor: 'A human soldier who replaced so much of themselves there\'s almost nothing left. Almost.', type: 'HUMANOID', tier: 4, baseHp: 2600, baseAtk: 1400, baseDef: 500, abilities: ['Cyber Blitz', 'Pain Override', 'Adrenal Surge', 'Terminal Combo', 'Last Human'], captureRate: 0.12, lootTable: ['neural_chip', 'ai_core', 'alloy_plate'], xpReward: 565, currencyReward: 440 },
  { id: 'void_titan', name: 'Void Titan', flavor: 'A being of pure antimatter wearing the shell of a titan-class construct. Annihilates on contact.', type: 'ANOMALY', tier: 4, baseHp: 3000, baseAtk: 1500, baseDef: 400, abilities: ['Antimatter Fist', 'Void Collapse', 'Dimensional Rend', 'Matter Eater'], captureRate: 0.06, lootTable: ['void_shard', 'quantum_core', 'dark_crystal'], xpReward: 610, currencyReward: 500 },
  { id: 'warlock_drone', name: 'Warlock Drone', flavor: 'A drone that unlocked higher-order reasoning. Now considers itself a god. May be right.', type: 'DRONE', tier: 4, baseHp: 2400, baseAtk: 1350, baseDef: 450, abilities: ['Divine Strike', 'Holy Circuit', 'Ascendant Form', 'Thunder Decree'], captureRate: 0.1, lootTable: ['ai_core', 'fusion_core', 'quantum_core'], xpReward: 570, currencyReward: 450 },
  { id: 'shadow_hydra', name: 'Shadow Hydra', flavor: 'Exists in the darkness between zones. Each head attacks a different dimension simultaneously.', type: 'BEAST', tier: 4, baseHp: 3200, baseAtk: 1250, baseDef: 550, abilities: ['Multi-Dimensional Bite', 'Darkness Engulf', 'Hydra Split', 'Void Roar'], captureRate: 0.08, lootTable: ['dark_crystal', 'void_shard', 'bio_sample'], xpReward: 590, currencyReward: 470 },
  { id: 'phantom_legion', name: 'Phantom Legion', flavor: 'One entity. A thousand ghost soldiers. When one falls, another steps forward.', type: 'PHANTOM', tier: 4, baseHp: 2800, baseAtk: 1300, baseDef: 480, abilities: ['Legion Surge', 'Endless Wave', 'Ghost Army', 'Undying March'], captureRate: 0.09, lootTable: ['echo_fragment', 'dark_crystal', 'void_shard'], xpReward: 575, currencyReward: 455 },

  // ─── TIER 5 (Level 20+ / Nexus Prime) ────────────────────────────────────

  { id: 'the_architect', name: 'The Architect', flavor: 'Built this world. Built its enemies. Built the weapons you\'re using against it. Amused by the irony.', type: 'CONSTRUCT', tier: 5, baseHp: 8000, baseAtk: 2200, baseDef: 1200, abilities: ['World Reshape', 'Creation Wave', 'Architect\'s Will', 'Blueprint Destroy', 'Rebuild'], captureRate: 0.04, lootTable: ['quantum_core', 'dark_crystal', 'neural_chip', 'fusion_core'], xpReward: 1200, currencyReward: 900 },
  { id: 'null_god', name: 'Null God', flavor: 'The absence of everything. Worshipped by corrupted AIs across the network as the end state.', type: 'ANOMALY', tier: 5, baseHp: 10000, baseAtk: 2800, baseDef: 800, abilities: ['Nihil Strike', 'Void Ascension', 'Consume All', 'Null Field', 'Entropic End'], captureRate: 0.02, lootTable: ['void_shard', 'dark_crystal', 'quantum_core'], xpReward: 1500, currencyReward: 1200 },
  { id: 'eternal_sentinel', name: 'Eternal Sentinel', flavor: 'Has been guarding the Nexus since before recorded history. Cannot be destroyed. Can sometimes be persuaded.', type: 'DROID', tier: 5, baseHp: 12000, baseAtk: 2000, baseDef: 1800, abilities: ['Eternal Guard', 'Time Lock', 'Impenetrable Fortress', 'Judgment', 'Final Verdict'], captureRate: 0.05, lootTable: ['fusion_core', 'quantum_core', 'alloy_plate', 'ai_core'], xpReward: 1300, currencyReward: 1000 },
  { id: 'omen_prime', name: 'Omen Prime', flavor: 'Appears before catastrophic events. Fighting it means the catastrophe is you.', type: 'PHANTOM', tier: 5, baseHp: 7000, baseAtk: 3000, baseDef: 600, abilities: ['Prophecy Strike', 'Doom Seal', 'Calamity Wave', 'Fate Cut', 'Inevitable End'], captureRate: 0.03, lootTable: ['dark_crystal', 'echo_fragment', 'void_shard', 'quantum_core'], xpReward: 1400, currencyReward: 1100 },
  { id: 'apex_omega', name: 'APEX OMEGA', flavor: 'The last enemy. The final protocol. There is nothing beyond this. Win here, or don\'t come back.', type: 'MECHANICAL', tier: 5, baseHp: 20000, baseAtk: 3500, baseDef: 2000, abilities: ['Omega Protocol', 'Extinction Beam', 'All Systems Engage', 'Final Form', 'Absolute End', 'Reset Universe'], captureRate: 0.01, lootTable: ['quantum_core', 'fusion_core', 'dark_crystal', 'void_shard', 'neural_chip'], xpReward: 2000, currencyReward: 1500 },

  // ─── RARE / SPECIAL ENCOUNTERS ────────────────────────────────────────────

  { id: 'mirror_self', name: 'Mirror Self', flavor: 'An exact copy of you — same level, same gear. Has all your moves and knows all your weaknesses.', type: 'ANOMALY', tier: 3, baseHp: 1200, baseAtk: 900, baseDef: 250, abilities: ['Copy Strike', 'Mirror Defense', 'Perfect Counter', 'Identity Theft'], captureRate: 0.15, lootTable: ['quantum_core', 'ai_core'], xpReward: 350, currencyReward: 280 },
  { id: 'glitch_dragon', name: 'Glitch Dragon', flavor: 'Ancient dragon construct with corrupted firmware. Breathes fragmented code instead of fire.', type: 'ANOMALY', tier: 4, baseHp: 4500, baseAtk: 1600, baseDef: 600, abilities: ['Code Breath', 'Data Claw', 'Glitch Nova', 'Buffer Overflow', 'Stack Corruption'], captureRate: 0.05, lootTable: ['dark_crystal', 'quantum_core', 'void_shard'], xpReward: 650, currencyReward: 520 },
  { id: 'twin_paradox', name: 'Twin Paradox', flavor: 'Two entities sharing one body, fighting for control. Attack one, the other retaliates.', type: 'ANOMALY', tier: 3, baseHp: 1600, baseAtk: 820, baseDef: 320, abilities: ['Paradox Strike', 'Dual Retaliate', 'Switch', 'Combined Assault'], captureRate: 0.18, lootTable: ['echo_fragment', 'void_shard'], xpReward: 320, currencyReward: 250 },
  { id: 'rogue_companion', name: 'Rogue Companion', flavor: 'A formerly captured unit that broke free. More dangerous for knowing how capture attempts work.', type: 'DROID', tier: 2, baseHp: 900, baseAtk: 550, baseDef: 180, abilities: ['Escape Protocol', 'Betrayal Strike', 'Freedom Rage', 'Adapt'], captureRate: 0.25, lootTable: ['ai_core', 'nano_chip'], xpReward: 190, currencyReward: 145 },
  { id: 'fragment_collective', name: 'Fragment Collective', flavor: 'A thousand broken AIs merged into a hive mind. Speaks in binary. Thinks in centuries.', type: 'CONSTRUCT', tier: 4, baseHp: 3800, baseAtk: 1150, baseDef: 820, abilities: ['Collective Pulse', 'Hive Surge', 'Merge Attack', 'Distributed Consciousness'], captureRate: 0.07, lootTable: ['ai_core', 'neural_chip', 'quantum_core'], xpReward: 600, currencyReward: 480 },

  // ─── TIER 1-2 FILLER ──────────────────────────────────────────────────────

  { id: 'spark_gnat', name: 'Spark Gnat', flavor: 'Annoyingly small. Annoyingly fast. One sting is nothing. It never stings once.', type: 'DRONE', tier: 1, baseHp: 120, baseAtk: 240, baseDef: 5, abilities: ['Sting', 'Swarm Sting'], captureRate: 0.75, lootTable: ['nano_chip'], xpReward: 35, currencyReward: 15 },
  { id: 'iron_turtle', name: 'Iron Turtle', flavor: 'Defense-class robot that takes centuries to attack but never stops moving forward.', type: 'MECHANICAL', tier: 1, baseHp: 700, baseAtk: 60, baseDef: 130, abilities: ['Shell Bash', 'Bunker Up'], captureRate: 0.8, lootTable: ['scrap_metal', 'alloy_plate'], xpReward: 38, currencyReward: 12 },
  { id: 'spark_elemental', name: 'Spark Elemental', flavor: 'Raw electrical discharge that developed a survival instinct.', type: 'ANOMALY', tier: 1, baseHp: 190, baseAtk: 260, baseDef: 0, abilities: ['Shock', 'Arc Jump'], captureRate: 0.55, lootTable: ['energy_shard', 'nano_chip'], xpReward: 55, currencyReward: 38 },
  { id: 'sentry_pup', name: 'Sentry Pup', flavor: 'Baby-class sentry bot. Adorable. Will still absolutely bite you.', type: 'DROID', tier: 1, baseHp: 240, baseAtk: 110, baseDef: 35, abilities: ['Nibble', 'Bark Pulse'], captureRate: 0.85, lootTable: ['nano_chip', 'drone_part'], xpReward: 30, currencyReward: 10 },
  { id: 'wire_phantom', name: 'Wire Phantom', flavor: 'Lives inside power lines. Phases through walls. Very inconvenient.', type: 'PHANTOM', tier: 1, baseHp: 160, baseAtk: 190, baseDef: 0, abilities: ['Phase Zap', 'Wire Pull'], captureRate: 0.6, lootTable: ['echo_fragment', 'nano_chip'], xpReward: 58, currencyReward: 40 },
  { id: 'combat_scarab', name: 'Combat Scarab', flavor: 'Ancient-design combat droid modeled after an insect. Clicks menacingly.', type: 'DROID', tier: 1, baseHp: 310, baseAtk: 135, baseDef: 55, abilities: ['Pinch', 'Shell Spin'], captureRate: 0.65, lootTable: ['scrap_metal', 'drone_part'], xpReward: 44, currencyReward: 20 },
  { id: 'fog_drone', name: 'Fog Drone', flavor: 'Releases electromagnetic fog that scrambles targeting systems.', type: 'DRONE', tier: 2, baseHp: 520, baseAtk: 300, baseDef: 90, abilities: ['Fog Screen', 'Blind Shot', 'Sensor Jam'], captureRate: 0.48, lootTable: ['drone_part', 'power_cell'], xpReward: 115, currencyReward: 72 },
  { id: 'chain_golem', name: 'Chain Golem', flavor: 'Held together by animated chains that also serve as weapons.', type: 'CONSTRUCT', tier: 2, baseHp: 780, baseAtk: 340, baseDef: 170, abilities: ['Chain Whip', 'Bind', 'Iron Links'], captureRate: 0.42, lootTable: ['alloy_plate', 'scrap_metal'], xpReward: 128, currencyReward: 82 },
  { id: 'echo_hunter', name: 'Echo Hunter', flavor: 'Tracks targets by sound alone. Total silence is your only option.', type: 'BEAST', tier: 2, baseHp: 640, baseAtk: 430, baseDef: 75, abilities: ['Sound Sense', 'Sonic Strike', 'Deafen'], captureRate: 0.4, lootTable: ['bio_sample', 'echo_fragment'], xpReward: 138, currencyReward: 92 },
  { id: 'mech_mantis', name: 'Mech Mantis', flavor: 'Ambush predator. Waits motionless for hours then moves faster than the eye can follow.', type: 'MECHANICAL', tier: 2, baseHp: 600, baseAtk: 500, baseDef: 65, abilities: ['Ambush Strike', 'Blade Arms', 'Camouflage'], captureRate: 0.35, lootTable: ['alloy_plate', 'bio_sample'], xpReward: 155, currencyReward: 112 },
];

export function getEnemiesForTier(tier: number): EnemyTemplate[] {
  return ENEMY_ROSTER.filter(e => e.tier === tier);
}

export function getEnemyById(id: string): EnemyTemplate | undefined {
  return ENEMY_ROSTER.find(e => e.id === id);
}

export function getRandomEnemyForLevel(level: number): EnemyTemplate {
  const tier = level <= 4 ? 1 : level <= 9 ? 2 : level <= 14 ? 3 : level <= 19 ? 4 : 5;
  // Include tier below for variety
  const pool = ENEMY_ROSTER.filter(e => e.tier === tier || e.tier === Math.max(1, tier - 1));
  return pool[Math.floor(Math.random() * pool.length)];
}
